remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Redis-Microcontroller Interfacing
description: Redis optimization and Interfacing with Raspberry-PI microcontrollers!
